-- MySQL Script generated by MySQL Workbench
-- 11/28/17 12:07:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `idQuestion` INT NOT NULL,
  `Question` VARCHAR(45) NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `téléphone` INT NULL,
  `mail` VARCHAR(45) NULL,
  `date de naissance` DATETIME NULL,
  `type` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `mot de passe` VARCHAR(45) NULL,
  `réponse` VARCHAR(45) NULL,
  `Question_idQuestion` INT NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `Question_idQuestion`),
  INDEX `fk_Utilisateur_Question1_idx` (`Question_idQuestion` ASC),
  CONSTRAINT `fk_Utilisateur_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `mydb`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `idCommande` INT NOT NULL,
  `date de réception` DATETIME NULL,
  `date de commande` DATETIME NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Type produit_has_Commande_Typeproduit_idType produit` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `Utilisateur_idUtilisateur`, `Type produit_has_Commande_Typeproduit_idType produit`),
  INDEX `fk_Commande_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Commande_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logement` (
  `idLogement` INT NOT NULL,
  `code postal` INT NULL,
  `adresse` VARCHAR(45) NULL,
  `nombre de pièce` INT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idLogement`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Logement_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Logement_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type pièce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type pièce` (
  `idType pièce` INT NOT NULL,
  `type de pièce` VARCHAR(45) NULL,
  PRIMARY KEY (`idType pièce`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CeMac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CeMac` (
  `idCeMac` INT NOT NULL,
  PRIMARY KEY (`idCeMac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pièce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pièce` (
  `idPièce` INT NOT NULL,
  `superficie` INT NULL,
  `Logement_idLogement` INT NOT NULL,
  `Logement_Utilisateur_idUtilisateur` INT NOT NULL,
  `Type pièce_idType pièce` INT NOT NULL,
  `CeMac_idCeMac` INT NOT NULL,
  PRIMARY KEY (`idPièce`, `Logement_idLogement`, `Logement_Utilisateur_idUtilisateur`, `Type pièce_idType pièce`, `CeMac_idCeMac`),
  INDEX `fk_Pièce_Logement1_idx` (`Logement_idLogement` ASC, `Logement_Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Pièce_Type pièce1_idx` (`Type pièce_idType pièce` ASC),
  INDEX `fk_Pièce_CeMac1_idx` (`CeMac_idCeMac` ASC),
  CONSTRAINT `fk_Pièce_Logement1`
    FOREIGN KEY (`Logement_idLogement` , `Logement_Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Logement` (`idLogement` , `Utilisateur_idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pièce_Type pièce1`
    FOREIGN KEY (`Type pièce_idType pièce`)
    REFERENCES `mydb`.`Type pièce` (`idType pièce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pièce_CeMac1`
    FOREIGN KEY (`CeMac_idCeMac`)
    REFERENCES `mydb`.`CeMac` (`idCeMac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `idProduit` INT NOT NULL,
  `état` VARCHAR(45) NULL,
  `catégorie` VARCHAR(45) NULL,
  `CeMac_idCeMac` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `CeMac_idCeMac`),
  INDEX `fk_Capteur_CeMac1_idx` (`CeMac_idCeMac` ASC),
  CONSTRAINT `fk_Capteur_CeMac1`
    FOREIGN KEY (`CeMac_idCeMac`)
    REFERENCES `mydb`.`CeMac` (`idCeMac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type produit` (
  `idType produit` INT NOT NULL,
  `type produit` VARCHAR(45) NULL,
  `stock` INT NULL,
  `Type produit_has_Commande_Type produit_idType produit` INT NOT NULL,
  PRIMARY KEY (`idType produit`, `Type produit_has_Commande_Type produit_idType produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donées`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donées` (
  `idDonées` INT NOT NULL,
  `time stop` DATETIME NULL,
  `donnée` VARCHAR(45) NULL,
  `Produit_idProduit` INT NOT NULL,
  `Produit_CeMac_idCeMac` INT NOT NULL,
  PRIMARY KEY (`idDonées`, `Produit_idProduit`, `Produit_CeMac_idCeMac`),
  INDEX `fk_Donées_Capteur1_idx` (`Produit_idProduit` ASC, `Produit_CeMac_idCeMac` ASC),
  CONSTRAINT `fk_Donées_Capteur1`
    FOREIGN KEY (`Produit_idProduit` , `Produit_CeMac_idCeMac`)
    REFERENCES `mydb`.`Produit` (`idProduit` , `CeMac_idCeMac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Panne` (
  `idPanne` INT NOT NULL,
  `problème` VARCHAR(45) NULL,
  `date de début` DATETIME NULL,
  `date de fin` DATETIME NULL,
  `Produit_idProduit` INT NOT NULL,
  `Produit_CeMac_idCeMac` INT NOT NULL,
  PRIMARY KEY (`idPanne`, `Produit_idProduit`, `Produit_CeMac_idCeMac`),
  INDEX `fk_Panne_Capteur1_idx` (`Produit_idProduit` ASC, `Produit_CeMac_idCeMac` ASC),
  CONSTRAINT `fk_Panne_Capteur1`
    FOREIGN KEY (`Produit_idProduit` , `Produit_CeMac_idCeMac`)
    REFERENCES `mydb`.`Produit` (`idProduit` , `CeMac_idCeMac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scénario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scénario` (
  `idScénario` INT NOT NULL,
  `heure` DATETIME NULL,
  `jour` VARCHAR(45) NULL,
  `valeur` INT NULL,
  PRIMARY KEY (`idScénario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domisep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domisep` (
  `idDomisep` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `téléphone` INT NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomisep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ` (
  `idFAQ` INT NOT NULL,
  `question` VARCHAR(45) NULL,
  `réponse` VARCHAR(45) NULL,
  PRIMARY KEY (`idFAQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande_has_Type produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande_has_Type produit` (
  `idCommande` INT NOT NULL,
  `idType produit` INT NOT NULL,
  `quantité` INT NULL,
  PRIMARY KEY (`idCommande`, `idType produit`),
  INDEX `fk_Commande_has_Type capteur_Type capteur1_idx` (`idType produit` ASC),
  INDEX `fk_Commande_has_Type capteur_Commande1_idx` (`idCommande` ASC),
  CONSTRAINT `fk_Commande_has_Type capteur_Commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `mydb`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Type capteur_Type capteur1`
    FOREIGN KEY (`idType produit`)
    REFERENCES `mydb`.`Type produit` (`idType produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit_has_Scénario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit_has_Scénario` (
  `Produit_idProduit` INT NOT NULL,
  `Produit_CeMac_idCeMac` INT NOT NULL,
  `Scénario_idScénario` INT NOT NULL,
  PRIMARY KEY (`Produit_idProduit`, `Produit_CeMac_idCeMac`, `Scénario_idScénario`),
  INDEX `fk_Capteur_has_Scénario_Scénario1_idx` (`Scénario_idScénario` ASC),
  INDEX `fk_Capteur_has_Scénario_Capteur1_idx` (`Produit_idProduit` ASC, `Produit_CeMac_idCeMac` ASC),
  CONSTRAINT `fk_Capteur_has_Scénario_Capteur1`
    FOREIGN KEY (`Produit_idProduit` , `Produit_CeMac_idCeMac`)
    REFERENCES `mydb`.`Produit` (`idProduit` , `CeMac_idCeMac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Capteur_has_Scénario_Scénario1`
    FOREIGN KEY (`Scénario_idScénario`)
    REFERENCES `mydb`.`Scénario` (`idScénario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
